server:
  port: 8083
spring:
  datasource:
    username: root
    password: ljhhh666
    url: jdbc:mysql://localhost:3306/comeback?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 200
        max-wait: 1
        max-idle: 10
        min-idle: 0
    timeout: 6000


mybatis-plus:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.springtemplate.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



#showSql
logging:
  config: classpath:logback-spring.xml

